name: Send Slack Messages
description: Send a Slack message on different occasions
inputs:
  slack_token:
    description: The O-Auth token from the GitHub App that sends the message
    required: true
  body:
    description: The release notes to use (can be markdown)
    required: false
runs:
  using: node16
  main: "dist/index.js"